server:
  port: 8080

spring:
  application:
    name: SmartExam
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_exam?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789zyx

ollama:
  url: http://localhost:11434
  model: gemma3:4b

auth:
  enabled: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

upload:
  avatar-path: E:/Spring/SmartExam/SmartExam_SpringBoot/uploads/avatars